name: OpenAPI UI
type: module
description: Provides plugin system for OpenAPI/Swagger Interface libraries.
core_version_requirement: ^10.1.3 || ^11
package: OpenAPI

# Information added by Drupal.org packaging script on 2024-07-10
version: '8.x-1.0-rc5'
project: 'openapi_ui'
datestamp: 1720623204
