<?php

/**
 * @file
 * Provides a new Views Field plugin for all entity fields.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rest_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.rest_views':
      // Return module description, features, and usage instructions.
      $output = '';
      $output .= '<p>' . t('This module enhances the REST export functionality in Views.') . '</p>';
      $output .= '<p>' . t('Note that these will only work in combination with the (serializable) field handlers.') . '</p>';
      $output .= '<p>' . t('Check the readme for more information.') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_views_data_alter().
 */
function rest_views_views_data_alter(array &$data): void {
  foreach ($data as $table_alias => $fields) {
    /** @var array[] $fields */
    foreach ($fields as $field_alias => $field) {
      // Find all handlers that use the core Field plugin.
      if (isset($field['field']['id']) && $field['field']['id'] === 'field') {
        // Add a second handler that uses the Rest Field plugin.
        if (isset($field['title'])) {
          $field['title'] = t('@field (serializable)', ['@field' => $field['title']]);
        }
        $field['field']['id'] = 'field_export';

        // Only expose the field handler as the others are redundant.
        unset($field['argument'], $field['filter'], $field['sort']);
        $data[$table_alias]["{$field_alias}_export"] = $field;
      }
    }
  }
}
