name: OpenAPI JSON:API
description: OpenAPI support for the JSON:API module.
type: module
package: Web Services
core_version_requirement: ^9.1 || ^10
dependencies:
  - openapi:openapi
  - schemata:schemata
  - schemata:schemata_json_schema

# Information added by Drupal.org packaging script on 2022-12-08
version: '3.0.4'
project: 'openapi_jsonapi'
datestamp: 1670513666
