name: Swagger UI for OpenAPI UI
type: module
description: Provides display of OpenAPI docs using the Swagger UI plugin.
core_version_requirement: ^8 || ^9 || ^10
package: OpenAPI
dependencies:
  - openapi_ui:openapi_ui

# Information added by Drupal.org packaging script on 2023-10-04
version: '8.x-1.0'
project: 'openapi_ui_swagger'
datestamp: 1696427757
