<?php

/**
 * @file
 * Contains user_pass_refresh_security.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_login_url_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_pass_refresh_security module.
    case 'help.page.user_pass_refresh_security':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User Pass refresh Security') . '</p>';
      return $output;

    default:
  }
}
