<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */
function sys_twig_extensions_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'sys_twig_extensions/admin';
}

function sys_twig_extensions_tariff_bands() {
  return array(
    'Verde' => t('Verde'),
    'Amarela' => t('Amarela'),
    'Vermelha' => t('Vermelha'),
  );
}

function sys_twig_extensions_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['header'] = array(
    '#type' => 'fieldset',
    '#title' => 'Header',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );    

  $form['header']['tariff_band'] = array(
    '#type' => 'fieldset',
    '#title' => 'Bandeira Tarifária',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );  
  
  $form['header']['tariff_band']['label'] = array(
    '#type' => 'fieldset',
    '#title' => 'Label',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );    

  $form['header']['tariff_band']['label']['tariff_band_label'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('tariff_band_label')
  );  
  
  $form['header']['tariff_band']['label']['tariff_band_label_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('tariff_band_label_en')
  );   

  $form['header']['tariff_band']['band'] = array(
    '#type' => 'select', 
    '#title' => t('Bandeira'), 
    '#options' => sys_twig_extensions_tariff_bands(),
    '#default_value' => theme_get_setting('band')
  );

  $form['header']['text'] = array(
    '#type' => 'fieldset',
    '#title' => 'Texto',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );      

  $form['header']['text']['text'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('text')
  );  
  
  $form['header']['text']['text_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('text_en')
  );    

  $form['header']['navigation'] = array(
    '#type' => 'fieldset',
    '#title' => 'Navegação',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );  
  
  $form['header']['navigation']['search'] = array(
    '#type' => 'fieldset',
    '#title' => 'Busca',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );    

  $form['header']['navigation']['search']['searchbar'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('searchbar')
  );  
  
  $form['header']['navigation']['search']['searchbar_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('searchbar_en')
  );      
  
  $form['footer'] = array(
    '#type' => 'fieldset',
    '#title' => 'Footer',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );  
  
  $form['footer']['copyright'] = array(
    '#type' => 'fieldset',
    '#title' => 'Copyright',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );  

  $form['footer']['copyright']['copyright'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('copyright')
  );  
  
  $form['footer']['copyright']['copyright_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('copyright_en')
  );    

  $form['footer']['social_networks'] = array(
    '#type' => 'fieldset',
    '#title' => 'Redes Sociais',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );  
  
  $form['footer']['social_networks']['social_networks_label'] = array(
    '#type' => 'fieldset',
    '#title' => 'Label',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );    
  
  $form['footer']['social_networks']['social_networks_label']['social_networks_label'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('social_networks_label')
  ); 
  
  $form['footer']['social_networks']['social_networks_label']['social_networks_label_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('social_networks_label_en')
  );   

  $form['footer']['social_networks']['facebook'] = array(
      '#type' => 'textarea',
      '#title' => 'Facebook',
      '#default_value' => theme_get_setting('facebook')
  );  
  
  $form['footer']['social_networks']['twitter'] = array(
      '#type' => 'textarea',
      '#title' => 'Twitter',
      '#default_value' => theme_get_setting('twitter')
  ); 
  
  $form['footer']['social_networks']['instagram'] = array(
      '#type' => 'textarea',
      '#title' => 'Instagram',
      '#default_value' => theme_get_setting('instagram')
  );   

  $form['footer']['social_networks']['youtube'] = array(
      '#type' => 'textarea',
      '#title' => 'Youtube',
      '#default_value' => theme_get_setting('youtube')
  ); 
  
  $form['footer']['social_networks']['youtube'] = array(
      '#type' => 'textarea',
      '#title' => 'Youtube',
      '#default_value' => theme_get_setting('youtube')
  );   

  $form['footer']['social_networks']['linkedin'] = array(
      '#type' => 'textarea',
      '#title' => 'Linkedin',
      '#default_value' => theme_get_setting('linkedin')
  );     

  $form['footer']['app'] = array(
    '#type' => 'fieldset',
    '#title' => 'App',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );   
  
  $form['footer']['app']['google_play'] = array(
    '#type' => 'fieldset',
    '#title' => 'Google Play',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );    

  $form['footer']['app']['google_play']['google_play_img'] = array(
      '#type' => 'managed_file',
      '#upload_location' => 'public://',
      '#title' => 'Imagem',
      '#default_value' => theme_get_setting('google_play_img'),
  );     

  $form['footer']['app']['google_play']['google_play_url'] = array(
      '#type' => 'textarea',
      '#title' => 'URL',
      '#default_value' => theme_get_setting('google_play_url')
  );     

  $form['footer']['app']['app_store'] = array(
    '#type' => 'fieldset',
    '#title' => 'App Store',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );     

  $form['footer']['app']['app_store']['app_store_img'] = array(
      '#type' => 'managed_file',
      '#upload_location' => 'public://',
      '#title' => 'Imagem',
      '#default_value' => theme_get_setting('app_store_img'),
  );     

  $form['footer']['app']['app_store']['app_store_url'] = array(
      '#type' => 'textarea',
      '#title' => 'URL',
      '#default_value' => theme_get_setting('app_store_url')
  );       

  $form['footer']['contact'] = array(
    '#type' => 'fieldset',
    '#title' => 'Contatos',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );   
  
  $form['footer']['contact']['phone'] = array(
    '#type' => 'fieldset',
    '#title' => 'Telefone',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );     

  $form['footer']['contact']['phone']['phone'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('phone')
  ); 
  
  $form['footer']['contact']['phone']['phone_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('phone_en')
  );   

  $form['footer']['contact']['talk'] = array(
    '#type' => 'fieldset',
    '#title' => 'Fale com a gente',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );     

  $form['footer']['contact']['talk']['talk'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('talk')
  ); 
  
  $form['footer']['contact']['talk']['talk_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('talk_en')
  );     

  $form['footer']['contact']['talk']['talk_url'] = array(
      '#type' => 'textarea',
      '#title' => 'URL',
      '#default_value' => theme_get_setting('talk_url')
  );       

  $form['footer']['contact']['talk_to_clara'] = array(
    '#type' => 'fieldset',
    '#title' => 'Fale com a clara',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );     

  $form['footer']['contact']['talk_to_clara']['talk_to_clara'] = array(
      '#type' => 'textarea',
      '#title' => 'Default',
      '#default_value' => theme_get_setting('talk_to_clara')
  ); 
  
  $form['footer']['contact']['talk_to_clara']['talk_to_clara_en'] = array(
      '#type' => 'textarea',
      '#title' => 'EN',
      '#default_value' => theme_get_setting('talk_to_clara_en')
  );      

  $form['footer']['contact']['talk_to_clara']['talk_to_clara_url'] = array(
      '#type' => 'textarea',
      '#title' => 'URL',
      '#default_value' => theme_get_setting('talk_to_clara_url')
  );   

  $form['footer']['contact']['talk_to_clara']['talk_to_clara_img'] = array(
      '#type' => 'managed_file',
      '#upload_location' => 'public://',
      '#title' => 'Imagem',
      '#default_value' => theme_get_setting('talk_to_clara_img'),
  );     
  
  $form['#validate'][] = 'sys_twig_extensions_form_system_theme_settings_validate';
  $form['#submit'][] = 'sys_twig_extensions_form_system_theme_settings_submit';  
}

function sys_twig_extensions_form_system_theme_settings_validate(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  $google_play_img = file_save_upload('google_play_img');
  $app_store_img = file_save_upload('app_store_img');
  $talk_to_clara_img = file_save_upload('talk_to_clara_img');

  if (isset($google_play_img)) {
    if ($google_play_img) {
      $values['google_play_img_upload'] = $google_play_img;
    }
  } 

  if (isset($app_store_img)) {
    if ($app_store_img) {
      $values['app_store_img_upload'] = $app_store_img;
    }
  }  

  if (isset($talk_to_clara_img)) {
    if ($talk_to_clara_img) {
      $values['talk_to_clara_img_upload'] = $talk_to_clara_img;
    }
  }    
}

function sys_twig_extensions_form_system_theme_settings_submit(&$form, FormStateInterface $form_state) {
  $google_play_img = $form_state->getValue('google_play_img');
  $google_play_img = reset($google_play_img);
  $google_play_img = \Drupal\file\Entity\File::load($google_play_img);

  $app_store_img = $form_state->getValue('app_store_img');
  $app_store_img = reset($app_store_img);
  $app_store_img = \Drupal\file\Entity\File::load($app_store_img);

  $talk_to_clara_img = $form_state->getValue('talk_to_clara_img');
  $talk_to_clara_img = reset($talk_to_clara_img);
  $talk_to_clara_img = \Drupal\file\Entity\File::load($talk_to_clara_img);

  if($google_play_img) {
      $google_play_img->setPermanent();
      $google_play_img->setPermanent();
      $google_play_img->save();      
  }   

  if($app_store_img) {
      $app_store_img->setPermanent();
      $app_store_img->setPermanent();
      $app_store_img->save();      
  }    
  
  if($talk_to_clara_img) {
      $talk_to_clara_img->setPermanent();
      $talk_to_clara_img->setPermanent();
      $talk_to_clara_img->save();      
  }      
}